### 메시지 생성 요청 (POST)
POST http://localhost:8080/messages/write
Content-Type: application/json

{
  "messageWriteDTO": {
    "channelId": "bc6fd3ee-b716-4041-870b-44f1eecdc2c2",
    "creatorId": "b687cfa9-62f2-4c1d-9797-21ee3072597d",
    "text": "nice!"
  },
  "binaryContentCreateDTO": [{
    "fileName": "test123",
    "contentType": "test123",
    "bytes": [0,1,0,0,1]
  }
  ]
}
### 메시지 전체 조회(GET)
GET http://localhost:8080/messages/bc6fd3ee-b716-4041-870b-44f1eecdc2c2
Content-Type: application/json

### 메시지 삭제 (DELETE)
DELETE http://localhost:8080/messages/dd90f65b-e9ef-4e05-bc01-1febeaf6ed0c