### 서버 생성 요청 (POST)
POST http://localhost:8080/servers/create
Content-Type: application/json

{
  "ownerId": "943f741a-0cf4-4eb6-87d1-a37b379ab1e1",
  "name": "test"
}
### 서버 가입
PUT http://localhost:8080/servers/join/461b763b-82d9-4253-ba6b-cdaab6ad2147
Content-Type: application/json

{
    "userId": "b687cfa9-62f2-4c1d-9797-21ee3072597d"
}
### 서버 탈퇴
PUT http://localhost:8080/servers/quit/{{channelId}}
Content-Type: application/json

{
    "userId": null
}

### 서버 전체 조회(GET)
GET http://localhost:8080/servers/7a8f2f27-87d4-4df9-b7d5-3f9d9ec922b0
Content-Type: application/json

### 서버 삭제 (DELETE)
DELETE http://localhost:8080/servers/delete/303f11e9-ea4d-498e-81bb-60019fe446d6